default:
  app_name: "polished_example_01"
  api_key: "eOl5hsOcGKOEev1F8OKtMcBtfw7ts5eJm1"

axion:
  db:
    dbname: "maestroz-app-prod"
    host: "127.0.0.1"
    port: 5432
    user: "maestrozwebsrv"
    password: "BitY6Jri#*Li"
  firebase:
    projectId: "z-connect-e6765"
