default:
  app_name: "polished_example_01"
  #api_key: "ybb5sptUuidLW51arHrCmH3bDVoL1XXcGa"
  #api_url: "https://auth-api-dev.polished.tech/v1"
  api_key: "eOl5hsOcGKOEev1F8OKtMcBtfw7ts5eJm1"
  api_url: "https://auth-api.polished.tech/v1"
